### ISSUE TITLE
Licensing of the library

### ISSUE THREAD

**Issue by tshikaboom** [NatanBiesmans/Arduino-POST-HTTP-Parser#3]
Hello!

I'm doing a project using your library, and would like to know what would be your opinion on the license of this project, so there wouldn't be any problems using your code, even though the source code itself is not complicated :-)

I won't be suggesting anything myself because you are the copyright holder, although TBH my project is MIT-licensed and an LGPL-like license would be nice for me. But you don't have to take my word to decide.

Cheers!

**Comment by NatanBiesmans** [comment]
Hey,

I believe in fair use of code :)
If you use it in any cool project just send me a PM, I'm always interested in seeing where my code ends up!

Greetz
